'use client';

import { FormEvent, useEffect, useMemo, useState } from 'react';
import { supabase } from '@/lib/supabase';

type Community={id:string;owner_id:string;slug:string;name:string;description:string;privacy:string;created_at:string};
type CommunityPost={post_id:string;author_id:string;body:string;created_at:string;name:string;username:string};

export default function CommunitiesPage(){
 const [uid,setUid]=useState<string|null>(null); const [communities,setCommunities]=useState<Community[]>([]); const [memberships,setMemberships]=useState<Set<string>>(new Set()); const [selected,setSelected]=useState<string|null>(null); const [posts,setPosts]=useState<CommunityPost[]>([]); const [name,setName]=useState(''); const [description,setDescription]=useState(''); const [privacy,setPrivacy]=useState<'public'|'private'>('public'); const [draft,setDraft]=useState(''); const [busy,setBusy]=useState(false);
 useEffect(()=>{void bootstrap();},[]); useEffect(()=>{if(selected)void loadPosts(selected);},[selected]);
 async function bootstrap(){const {data:{user}}=await supabase.auth.getUser();if(!user){location.href='/auth';return;}setUid(user.id);await loadCommunities(user.id);}
 async function loadCommunities(userId:string){const [{data:c},{data:m}]=await Promise.all([supabase.from('communities').select('*').order('created_at',{ascending:false}).limit(100),supabase.from('community_members').select('community_id').eq('user_id',userId)]);const rows=(c??[]) as Community[];setCommunities(rows);setMemberships(new Set((m??[]).map((x:any)=>x.community_id)));if(!selected&&rows[0])setSelected(rows[0].id);}
 async function loadPosts(communityId:string){const {data:links}=await supabase.from('community_posts').select('post_id,author_id,created_at').eq('community_id',communityId).order('created_at',{ascending:false}).limit(100);const rows=(links??[]) as {post_id:string;author_id:string;created_at:string}[];if(!rows.length){setPosts([]);return;}const postIds=rows.map(x=>x.post_id),authorIds=[...new Set(rows.map(x=>x.author_id))];const [{data:p},{data:profiles}]=await Promise.all([supabase.from('posts').select('id,body').in('id',postIds).is('deleted_at',null),supabase.from('profiles').select('id,display_name,username').in('id',authorIds)]);const postMap=new Map((p??[]).map((x:any)=>[x.id,x.body]));const profileMap=new Map((profiles??[]).map((x:any)=>[x.id,x]));setPosts(rows.map(x=>({post_id:x.post_id,author_id:x.author_id,body:postMap.get(x.post_id)??'',created_at:x.created_at,name:profileMap.get(x.author_id)?.display_name??'Chirpx User',username:profileMap.get(x.author_id)?.username??'chirpx'})));}
 async function createCommunity(e:FormEvent){e.preventDefault();if(!uid||!name.trim())return;setBusy(true);const slug=name.trim().toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,45);const finalSlug=`${slug || 'community'}-${crypto.randomUUID().slice(0,6)}`;const {data,error}=await supabase.from('communities').insert({owner_id:uid,name:name.trim(),slug:finalSlug,description:description.trim(),privacy}).select('id').single();if(error)alert(error.message);else{setName('');setDescription('');await loadCommunities(uid);if(data?.id)setSelected(data.id);}setBusy(false);}
 async function join(c:Community){if(!uid)return;const {error}=await supabase.from('community_members').insert({community_id:c.id,user_id:uid,role:'member'});if(error)alert(error.message);else setMemberships(s=>new Set(s).add(c.id));}
 async function leave(c:Community){if(!uid||c.owner_id===uid)return;const {error}=await supabase.from('community_members').delete().eq('community_id',c.id).eq('user_id',uid);if(error)alert(error.message);else setMemberships(s=>{const n=new Set(s);n.delete(c.id);return n;});}
 async function publish(){if(!uid||!selected||!draft.trim()||!memberships.has(selected))return;const body=draft.trim();setBusy(true);const {data:post,error}=await supabase.from('posts').insert({author_id:uid,kind:'chirp',visibility:'public',body}).select('id').single();if(error||!post){alert(error?.message??'Could not publish');setBusy(false);return;}const link=await supabase.from('community_posts').insert({community_id:selected,post_id:post.id,author_id:uid});if(link.error)alert(link.error.message);else{setDraft('');await loadPosts(selected);}setBusy(false);}
 const active=useMemo(()=>communities.find(c=>c.id===selected)??null,[communities,selected]);
 return <main style={{maxWidth:1160,margin:'0 auto',padding:20}}><div style={{display:'flex',alignItems:'center',gap:18}}><a href="/" className="brand">Chirp<span>x</span></a><h1>Communities</h1></div><div style={{display:'grid',gridTemplateColumns:'minmax(280px,360px) 1fr',gap:16}}>
  <aside style={{display:'grid',gap:14,alignContent:'start'}}><form className="card" onSubmit={createCommunity} style={{padding:16,display:'grid',gap:10}}><h3>Create a community</h3><input value={name} onChange={e=>setName(e.target.value)} placeholder="Community name" required minLength={3} maxLength={80} style={field}/><textarea value={description} onChange={e=>setDescription(e.target.value)} placeholder="What is this community about?" maxLength={1000} style={{...field,minHeight:80}}/><select value={privacy} onChange={e=>setPrivacy(e.target.value as 'public'|'private')} style={field}><option value="public">Public</option><option value="private">Private</option></select><button className="primary" disabled={busy}>{busy?'Creating…':'Create community'}</button></form><section className="card" style={{padding:12}}><h3>Discover</h3>{communities.map(c=><button key={c.id} onClick={()=>setSelected(c.id)} style={{width:'100%',textAlign:'left',padding:12,marginBottom:8,border:'1px solid #253041',borderRadius:12,background:selected===c.id?'#182335':'#111821',color:'inherit'}}><b>{c.name}</b><div className="muted">/{c.slug} · {c.privacy}</div></button>)}</section></aside>
  <section className="card" style={{overflow:'hidden'}}>{active?<><header style={{padding:20,borderBottom:'1px solid #253041'}}><div style={{display:'flex',justifyContent:'space-between',gap:12,alignItems:'center'}}><div><h2 style={{margin:0}}>{active.name}</h2><div className="muted">/{active.slug} · {active.privacy}</div></div>{memberships.has(active.id)?(active.owner_id===uid?<span className="muted">Owner</span>:<button className="tab" onClick={()=>void leave(active)}>Leave</button>):active.privacy==='public'?<button className="primary" onClick={()=>void join(active)}>Join</button>:<span className="muted">Private community</span>}</div><p>{active.description}</p></header>{memberships.has(active.id)&&<div style={{padding:16,borderBottom:'1px solid #253041'}}><textarea value={draft} onChange={e=>setDraft(e.target.value)} placeholder={`Post to ${active.name}`} maxLength={10000} style={{...field,width:'100%',minHeight:90}}/><div style={{textAlign:'right',marginTop:8}}><button className="primary" disabled={!draft.trim()||busy} onClick={()=>void publish()}>Post</button></div></div>}<div>{posts.length===0?<p className="muted" style={{padding:20}}>No community posts yet.</p>:posts.map(p=><article className="post" key={p.post_id}><div className="avatar">{p.name.slice(0,2).toUpperCase()}</div><div><div className="meta"><a className="name" href={`/profile/${p.username}`}>{p.name}</a><span className="handle">@{p.username}</span><span className="time">· {new Date(p.created_at).toLocaleString()}</span></div><p className="body">{p.body}</p></div></article>)}</div></>:<p className="muted" style={{padding:20}}>Choose or create a community.</p>}</section>
 </div></main>;
}
const field={padding:12,borderRadius:12,border:'1px solid #253041',background:'#151c26',color:'white'};
