'use client';

import { FormEvent, useEffect, useMemo, useState } from 'react';
import { supabase } from '@/lib/supabase';

type Conversation={id:string;created_by:string;direct_user_id:string|null;kind:string;title:string|null;updated_at:string};
type Profile={id:string;username:string;display_name:string};
type Message={id:string;conversation_id:string;sender_id:string;body:string;created_at:string};
type SearchResult={result_type:string;id:string;title:string;subtitle:string;rank:number};

export default function MessagesPage(){
 const [uid,setUid]=useState<string|null>(null); const [conversations,setConversations]=useState<Conversation[]>([]); const [profiles,setProfiles]=useState<Map<string,Profile>>(new Map()); const [selected,setSelected]=useState<string|null>(null); const [messages,setMessages]=useState<Message[]>([]); const [draft,setDraft]=useState(''); const [q,setQ]=useState(''); const [people,setPeople]=useState<SearchResult[]>([]); const [busy,setBusy]=useState(false);
 useEffect(()=>{void bootstrap();},[]);
 useEffect(()=>{if(!selected)return;void loadMessages(selected);const channel=supabase.channel(`messages:${selected}`).on('postgres_changes',{event:'INSERT',schema:'public',table:'messages',filter:`conversation_id=eq.${selected}`},payload=>{const row=payload.new as Message;setMessages(current=>current.some(m=>m.id===row.id)?current:[...current,row]);}).subscribe();return()=>{void supabase.removeChannel(channel);};},[selected]);
 async function bootstrap(){const {data:{user}}=await supabase.auth.getUser();if(!user){location.href='/auth';return;}setUid(user.id);await loadConversations(user.id);}
 async function loadConversations(userId:string){const {data}=await supabase.from('conversations').select('id,created_by,direct_user_id,kind,title,updated_at').order('updated_at',{ascending:false});const rows=(data??[]) as Conversation[];setConversations(rows);const otherIds=[...new Set(rows.map(c=>c.kind==='direct'?(c.created_by===userId?c.direct_user_id:c.created_by):null).filter(Boolean) as string[])];if(otherIds.length){const {data:p}=await supabase.from('profiles').select('id,username,display_name').in('id',otherIds);setProfiles(new Map(((p??[]) as Profile[]).map(x=>[x.id,x])));}if(!selected&&rows[0])setSelected(rows[0].id);}
 async function loadMessages(conversationId:string){const {data}=await supabase.from('messages').select('id,conversation_id,sender_id,body,created_at').eq('conversation_id',conversationId).is('deleted_at',null).order('created_at',{ascending:true}).limit(200);setMessages((data??[]) as Message[]);if(uid)await supabase.from('conversation_members').update({last_read_at:new Date().toISOString()}).eq('conversation_id',conversationId).eq('user_id',uid);}
 async function searchPeople(e:FormEvent){e.preventDefault();if(!q.trim())return;const {data}=await supabase.rpc('search_chirpx',{search_term:q.trim(),limit_count:20});setPeople(((data??[]) as SearchResult[]).filter(r=>r.result_type==='profile'&&r.id!==uid));}
 async function startDm(targetId:string){if(!uid)return;setBusy(true);const existing=conversations.find(c=>c.kind==='direct'&&((c.created_by===uid&&c.direct_user_id===targetId)||(c.created_by===targetId&&c.direct_user_id===uid)));if(existing){setSelected(existing.id);setPeople([]);setBusy(false);return;}const {data,error}=await supabase.from('conversations').insert({created_by:uid,kind:'direct',direct_user_id:targetId}).select('id').single();if(error){await loadConversations(uid);const retry=conversations.find(c=>c.kind==='direct'&&((c.created_by===uid&&c.direct_user_id===targetId)||(c.created_by===targetId&&c.direct_user_id===uid)));if(retry)setSelected(retry.id);}else if(data?.id){await loadConversations(uid);setSelected(data.id);}setPeople([]);setBusy(false);}
 async function send(){if(!uid||!selected||!draft.trim())return;const body=draft.trim();setDraft('');const {error}=await supabase.from('messages').insert({conversation_id:selected,sender_id:uid,body});if(error){setDraft(body);alert(error.message);}}
 const active=useMemo(()=>conversations.find(c=>c.id===selected)??null,[conversations,selected]);const activeOther=active&&uid?profiles.get(active.created_by===uid?(active.direct_user_id??''):active.created_by):undefined;
 return <main style={{maxWidth:1100,margin:'0 auto',padding:20}}><div style={{display:'flex',alignItems:'center',gap:18}}><a href="/" className="brand">Chirp<span>x</span></a><h1>Messages</h1></div><div style={{display:'grid',gridTemplateColumns:'minmax(260px,340px) 1fr',gap:16,minHeight:'72vh'}}>
  <aside className="card" style={{padding:14,overflow:'auto'}}><form onSubmit={searchPeople} style={{display:'flex',gap:8}}><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Find someone" style={{minWidth:0,flex:1,padding:10,borderRadius:10,border:'1px solid #253041',background:'#151c26',color:'white'}}/><button className="primary">Find</button></form>{people.length>0&&<div style={{marginTop:10}}>{people.map(p=><button key={p.id} disabled={busy} onClick={()=>void startDm(p.id)} style={{display:'block',width:'100%',textAlign:'left',padding:10,background:'transparent',color:'inherit',border:0,borderBottom:'1px solid #202a38'}}><b>{p.title}</b><div className="muted">@{p.subtitle}</div></button>)}</div>}<h3>Conversations</h3>{conversations.map(c=>{const otherId=uid?(c.created_by===uid?c.direct_user_id:c.created_by):null;const p=otherId?profiles.get(otherId):undefined;return <button key={c.id} onClick={()=>setSelected(c.id)} style={{display:'block',width:'100%',padding:12,textAlign:'left',border:'1px solid #253041',borderRadius:12,marginBottom:8,background:selected===c.id?'#182335':'#111821',color:'inherit'}}><b>{c.kind==='direct'?(p?.display_name??'Chirpx user'):(c.title??'Group')}</b>{p&&<div className="muted">@{p.username}</div>}</button>;})}</aside>
  <section className="card" style={{display:'grid',gridTemplateRows:'auto 1fr auto',overflow:'hidden'}}><header style={{padding:16,borderBottom:'1px solid #253041'}}><b>{activeOther?.display_name??active?.title??'Select a conversation'}</b>{activeOther&&<div className="muted">@{activeOther.username}</div>}</header><div style={{padding:16,overflowY:'auto',display:'flex',flexDirection:'column',gap:10}}>{messages.map(m=><div key={m.id} style={{alignSelf:m.sender_id===uid?'flex-end':'flex-start',maxWidth:'75%',padding:'10px 12px',borderRadius:14,background:m.sender_id===uid?'#e91e63':'#1a2431'}}><div>{m.body}</div><small style={{opacity:.65}}>{new Date(m.created_at).toLocaleTimeString()}</small></div>)}</div><div style={{display:'flex',gap:10,padding:14,borderTop:'1px solid #253041'}}><input value={draft} onChange={e=>setDraft(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();void send();}}} disabled={!selected} placeholder="Write a message" style={{flex:1,padding:12,borderRadius:12,border:'1px solid #253041',background:'#151c26',color:'white'}}/><button className="primary" onClick={()=>void send()} disabled={!selected||!draft.trim()}>Send</button></div></section>
 </div></main>;
}
